config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/koala', to: 'pages#koala', as: 'koala'
  get '/papelitos', to: 'pages#papelitos', as: 'papelitos'
  resources :tasks
  resources :notifications, defaults: { format: :json }
  resources :playing_cards, only: :destroy
  resources :teams, only: [:index, :show, :new, :create]
  resources :players, only: [:index, :create]
  resources :papers, only: [:index, :new, :create, :update]
  get '/papelitos/reset', to: "papers#reset", as: 'reset_papelitos'
  require "sidekiq/web"
    authenticate :user, lambda { |u| u.admin } do
      mount Sidekiq::Web => '/sidekiq'
    end
  get '/service-worker.js', to: "service_worker#service_worker"
  get '/manifest.json', to: "service_worker#manifest"
  get '/offline.html', to: "service_worker#offline"
  root to: 'pages#home'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<h1 class="text-center font-size-24 font-bold">
  <%= link_to "El Mike Services", root_path  %>
  <i class="fas fa-copyright"></i>
</h1>
<p class="text-center font-size-14">La plataforma web <%= complementary_text %></p>
  <div class="header-copyright">
    <div class="header-copyright-share-whatsapp">
      <a href="https://wa.me/?text=<%= URI.encode(root_url) %>">Compartir <i class="fab fa-whatsapp"></i></a>
    </div>
    <div class="header-copyright-made-by">
        Made with <i class="fa fa-heart"></i> By:<a href="https://www.instagram.com/somos_scuad/" target="_blank"> Mike @somos_scuad <i class="fab fa-instagram"></i></a>
    </div>
  </div>
<hr class="header-separator">

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_player-card.html.erb
<li data-id ="<%= player.id %>" data-target="players.player" class="list-group-item">
  <%= player.nickname %>
  <% if player.ready_to_play? %>
    <i class="em em-white_check_mark"></i>
  <% else %>
    <i class="em em-x"></i>
  <% end %>
</li>

app/views/shared/_player-form.html.erb
<%= simple_form_for Player.new, remote: true, html: { "data-action": "ajax:success->players#clearForm"   } do |f| %>
  <div class="col-xs-6">
    <%=f.input :nickname, input_html: { autocomplete: "off" } %>
  </div>
  <div class="col-xs-6">
    <%= f.association :team, input_html: { autocomplete: "off" } %>
  </div>
  <div class="col-xs-12">
  <%= f.submit "Agregar", class: "btn order-more-button" %>
  </div>
<% end %>

app/views/shared/_playing-card.html.erb
<div
  data-controller="playing-card"
  data-action="click->playing-card#remove"
  data-id="<%= playing_card.id %>"
  class="outline <%= "red" if playing_card.category == "&diams;" || playing_card.category == "&hearts;"%>"
>
  <div class="top"><span><%= playing_card.number %></span><span><%== playing_card.category %></span></div>
  <div class="center">
    <% if number_of_k == 1 && playing_card.number =="K"  %>
      <p>LLORELA TOMA EL KOALA (4/4)</p>
    <% elsif playing_card.number =="K"%>
      <p><%= playing_card.rule %>(<%=4 - number_of_k + 1%>/4)</p>
    <% else %>
      <p><%= playing_card.rule %></p>
    <% end %>
    <h1><%== playing_card.category %></h1>
  </div>
  <div class="bottom"><span><%== playing_card.category %></span><span><%= playing_card.number %></span></div>
</div>

app/views/shared/_task-card.html.erb
<div
  class="order-news <%= "tachado" if task.status %>"
  data-id="<%= task.id %>"
  data-controller="task"
  data-channel="task"
  data-target="tasks.task"
>
    <div class="message">
      <%= feed_photo_or_generic(task.user.downcase) %>
      <div class="message-name">
        <div class="table-name-and-date">
          <div class="full_name">
            <h3><%= task.user.capitalize %></h3>
          </div>
          <div class="time_ago">
            <p>hace <%= distance_of_time_in_words(Time.now, task.created_at) %>.</p>
          </div>
        </div>
        <p>Pidió <strong><%= task.description %></strong>.  <i class="em <%= @icons.sample(1)[0].to_s %>"></i> </p>
      </div>
    </div>
    <div class="update-action hidden" data-target="task.updateActions">
      <%= link_to "Borrar", task_path(task), method: "DELETE", remote: true, class: "red", data: { confirm: "Seguro?" } %>
      <% text = task.status ? "Deshacer" : "Completar" %>
      <%= link_to text, task_path(task), method: "PATCH", remote: true , class: "complete-task-btn" %>
    </div>
</div>

app/views/shared/_task-form.html.erb
<%= simple_form_for task, remote: true do |f| %>
  <%= f.input :status, as: :hidden, input_html: { value: false } %>
  <div class="col-xs-6">
    <%= f.input :description, label: "¿Qué necesitas?", placeholder: "Ej: Una costeñita", input_html: { autocomplete: "off" } %>
  </div>
  <div class="col-xs-6">
    <%= f.input :user, label: "¿Quién eres?", placeholder: "Ej: El Mike", input_html: { autocomplete: "off" } %>
  </div>
  <div class="col-xs-12">
    <% text_options = %w[#HelpMeMike #AuuidaMike #TirateUn14Mike #HacemeUnCruceMike, #MikeVosQueSosMúsicoHacemeUnFa] %>
    <%= button_tag type: 'submit', class: "btn order-more-button" do %>
      <%= text_options.sample %>
      <i class="fas fa-medkit"></i>
    <% end %>
  </div>
<% end %>