config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/koala', to: 'pages#koala', as: 'koala'
  get '/papelitos', to: 'pages#papelitos', as: 'papelitos'
  resources :tasks
  resources :notifications, defaults: { format: :json }
  resources :playing_cards, only: :destroy
  resources :teams, only: [:index, :show, :new, :create]
  resources :players, only: [:index, :create]
  resources :papers, only: [:index, :new, :create, :update]
  get '/papelitos/reset', to: "papers#reset", as: 'reset_papelitos'
  require "sidekiq/web"
    authenticate :user, lambda { |u| u.admin } do
      mount Sidekiq::Web => '/sidekiq'
    end
  get '/service-worker.js', to: "service_worker#service_worker"
  get '/manifest.json', to: "service_worker#manifest"
  get '/offline.html', to: "service_worker#offline"
  root to: 'pages#home'
end

app/models/paper.rb
class Paper < ApplicationRecord
  belongs_to :team, optional: true
  belongs_to :player
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  skip_before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: :update

  def index
    @papers = Paper.where(count: params[:count].to_i).where(team: nil).order('random()')
    @team1 = Team.first
    @team2 = Team.second
  end

  def new
  end

  def create
    player = Player.find(JSON.parse(cookies[:player])["id"])
    rounds = [1, 2, 3]
    rounds.each do |round|
      Paper.create(description: params[:paper][:paper_1], player: player, count: round)
      Paper.create(description: params[:paper][:paper_2], player: player, count: round)
      Paper.create(description: params[:paper][:paper_3], player: player, count: round)
    end
    change_player_status(player.id)
    redirect_to players_path
  end

  def update
    @paper = Paper.find(params[:id])
    @paper.update(paper_params)
    render json: 200
  end

  def reset
    cookies[:player] = nil
    Team.destroy_all
    Player.destroy_all
    redirect_to papelitos_path
    ActionCable.server.broadcast "player", { action: "game_restart" }
    $redis.set("button_changes", 0)
  end

  private

  def paper_params
    params.require(:paper).permit(:team_id, :count)
  end

  def change_player_status(player_id)
    ActionCable.server.broadcast "player", {
      action: "change_player_status",
      icon: "<i class='em em-white_check_mark'></i>",
      playerId: player_id
    }
  end
end

app/views/papers/index.html.erb
<div
  class="paper-cards-container"
  data-controller="papers"
  data-papers-team-id-left="<%= @team1.id %>"
  data-papers-team-id-right="<%= @team2.id %>"
  data-papers-check-papers-interval=1000
  data-papers-redirect-url="<%= players_path %>"
>
  <h4 class="text-center" id="timer" data-target="papers.timer">1:00</h3>
  <div class="cards-container">
    <% @papers.each do |paper| %>
      <div class="card-item" data-fetch-url="<%= paper_path paper %>" data-count="<%= paper.count %>" data-target="papers.card" >
        <%= paper.description %>
      </div>
    <% end %>
  </div>
  <div class="global-actions">
    <div class="action action--left" data-action="click->papers#pointForLeftTeam"><%= @team1.name %></div>
    <div class="action action--center" data-action="click->papers#unblockButtonOnClients" >
      <%= link_to "Volver", players_path %>
    </div>
    <div class="action action--right" data-action="click->papers#pointForRightTeam"><%= @team2.name %></div>
  </div>
</div>

app/views/papers/new.html.erb
<div class="container wrapper">
  <%= render 'shared/header', complementary_text: "del entretenimiento" %>
  <h3 class="text-center font-size-16 font-lighter">Crea los papelitos:</h3>
  <%= form_with model: Paper.new, local: true do |f| %>
  <div class="form-group">
    <%= f.label :paper_1, "Papelito 1" %>
    <%= f.text_field :paper_1, class: "form-control", autocomplete: "off" %>
  </div>
  <div class="form-group">
    <%= f.label :paper_2, "Papelito 2" %>
    <%= f.text_field :paper_2, class: "form-control", autocomplete: "off" %>
  </div>
  <div class="form-group">
    <%= f.label :paper_3, "Papelito 3" %>
    <%= f.text_field :paper_3, class: "form-control", autocomplete: "off" %>
  </div>
    <%= f.submit "Crear papelitos", class: "btn order-more-button" %>
  <% end %>
</div>