config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/koala', to: 'pages#koala', as: 'koala'
  get '/papelitos', to: 'pages#papelitos', as: 'papelitos'
  resources :tasks
  resources :notifications, defaults: { format: :json }
  resources :playing_cards, only: :destroy
  resources :teams, only: [:index, :show, :new, :create]
  resources :players, only: [:index, :create]
  resources :papers, only: [:index, :new, :create, :update]
  get '/papelitos/reset', to: "papers#reset", as: 'reset_papelitos'
  require "sidekiq/web"
    authenticate :user, lambda { |u| u.admin } do
      mount Sidekiq::Web => '/sidekiq'
    end
  get '/service-worker.js', to: "service_worker#service_worker"
  get '/manifest.json', to: "service_worker#manifest"
  get '/offline.html', to: "service_worker#offline"
  root to: 'pages#home'
end

app/models/player.rb
class Player < ApplicationRecord
  after_create_commit :add_player_to_game

  belongs_to :team
  belongs_to :user, optional: true
  has_many :papers, dependent: :destroy

  def papers_size
    papers.size / 3
  end

  def ready_to_play?
    papers.size == 9
  end

  def add_player_to_game
    ActionCable.server.broadcast "player", {
      action: "add_player",
      player: ApplicationController.render(
              partial: 'shared/player-card',
              locals: { player: self }
            ).squish,
      teamId: team.id
    }
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @teams = Team.all
    @teams_ready = @teams.all? { |team| team.players.size >= 2 }
    @papers_round1 = Paper.where(count: 1).where(team: nil)
    @papers_round2 = Paper.where(count: 2).where(team: nil)
    @papers_round3 = Paper.where(count: 3).where(team: nil)
    @current_player = Player.find(JSON.parse(cookies[:player])["id"]) if cookies[:player].present?
    @users_ready = Player.all.all?(&:ready_to_play?)
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      cookies[:player] = { value: @player.to_json, expires: 12.hours }
      respond_to do |format|
        format.html {
          redirect_to players_path
        }
      end
    else
      respond_to do |format|
        format.html {
          @teams = Team.all
          render 'index'
        }
        format.js {
          render json: { errors: @player.errors,},
                status: :unprocessable_entity
        }
      end
    end
  end

  private

  def player_params
    params.require(:player).permit(:nickname, :team_id, :user_id)
  end
end

app/views/players/index.html.erb
<div class="players-wrapper" data-controller="players">
  <div class="container wrapper">
    <%= render 'shared/header', complementary_text: "del entretenimiento" %>
    <%= link_to reset_papelitos_path do  %>
      <div class="text-right font-size-12 restart-btn">
        Reiniciar
        <i class="fas fa-redo"></i>
      </div>
    <% end %>
    <h3 class="text-center font-size-16 font-lighter mt-8">
      <% if @teams_ready %>
        Acá verás los resultados
      <% else %>
        Agrega los jugadores a cada equipo:
      <% end %>
    </h3>
    <div class="team-cards-container">
      <% @teams.each do |team| %>
      <div class="team-card" data-target="players.team" data-id="<%= team.id %>">
          <h3 class="text-center font-size-16 font-bold"><%= team.name %></h3>
          <h3 class="text-center font-size-16 font-bold mt-0 team-points">
            <%= "(#{pluralize(team.points, "Punto", "Puntos")} )" if team.points.positive? %>
          </h3>
          <ul class="list-group list-group-flush font-size-13">
            <% team.players.each do |player| %>
              <%= render 'shared/player-card', player: player %>
            <% end %>
          </ul>
      </div>
      <% end %>
    </div>
  </div>

  <template data-target="players.addPapersLink">
    <%= link_to "Agregar Papelitos", new_paper_path, class: "btn order-more-button"  %>
  </template>
  <template data-target="players.round1Link">
    <%= link_to "Ronda 1: Describir", papers_path(count: 1), class: "btn order-more-button"  %>
  </template>
  <template data-target="players.round2Link">
    <%= link_to "Ronda 2: Dramatizar", papers_path(count: 2), class: "btn order-more-button"  %>
  </template>
  <template data-target="players.round3Link">
    <%= link_to "Ronda 3: Solo 1 Palabra", papers_path(count: 3), class: "btn order-more-button"  %>
  </template>
  <template data-target="players.newGameLink">
    <%= link_to "Nueva partida", reset_papelitos_path, class: "btn order-more-button" %>
  </template>

  <div class="footer navbar-fixed-bottom text-center" data-target="players.footer">
    <div class="row">
      <% if cookies[:player].blank? %>
        <%= render 'shared/player-form' %>
      <% elsif @users_ready  && @papers_round1.size > 0 && @teams_ready %>
        <%= link_to "Ronda 1: Describir", papers_path(count: 1), class: "btn order-more-button"  %>
      <% elsif @users_ready  && @papers_round2.size > 0 && @teams_ready %>
        <%= link_to "Ronda 2: Dramatizar", papers_path(count: 2), class: "btn order-more-button"  %>
      <% elsif @users_ready  && @papers_round3.size > 0 && @teams_ready %>
        <%= link_to "Ronda 3: Solo 1 Palabra", papers_path(count: 3), class: "btn order-more-button"  %>
      <% elsif @current_player && @current_player.papers.size == 0 %>
        <%= link_to "Agregar Papelitos", new_paper_path, class: "btn order-more-button"  %>
      <% elsif Paper.where(team: nil).size == 0 %>
        <%= link_to "Nueva partida", reset_papelitos_path, class: "btn order-more-button" %>
      <% else %>
      <div class="alert alert-warning" role="alert">
        Faltan Jugadores para esta partida
      </div>
      <% end %>
    </div>
  </div>

</div>