config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/koala', to: 'pages#koala', as: 'koala'
  get '/papelitos', to: 'pages#papelitos', as: 'papelitos'
  resources :tasks
  resources :notifications, defaults: { format: :json }
  resources :playing_cards, only: :destroy
  resources :teams, only: [:index, :show, :new, :create]
  resources :players, only: [:index, :create]
  resources :papers, only: [:index, :new, :create, :update]
  get '/papelitos/reset', to: "papers#reset", as: 'reset_papelitos'
  require "sidekiq/web"
    authenticate :user, lambda { |u| u.admin } do
      mount Sidekiq::Web => '/sidekiq'
    end
  get '/service-worker.js', to: "service_worker#service_worker"
  get '/manifest.json', to: "service_worker#manifest"
  get '/offline.html', to: "service_worker#offline"
  root to: 'pages#home'
end

app/controllers/service_worker_controller.rb
class ServiceWorkerController < ApplicationController
  skip_before_action :authenticate_user!
  protect_from_forgery except: :service_worker

  def service_worker
  end

  def manifest
  end

  def offline
  end
end

app/views/service_worker/manifest.json.erb
{ "name": "El Mike Services",
  "short_name": "Mike Services",
  "start_url": "<%= root_path %>",
  "icons": [
    {
      "src": "<%= asset_path('heart-36x36.png') %>",
      "type": "image/png",
      "sizes": "36x36"
    },
    {
      "src": "<%= asset_path('heart-48x48.png') %>",
      "type": "image/png",
      "sizes": "48x48"
    },
    {
      "src": "<%= asset_path('heart-60x60.png') %>",
      "type": "image/png",
      "sizes": "60x60"
    },
    {
      "src": "<%= asset_path('heart-72x72.png') %>",
      "type": "image/png",
      "sizes": "72x72"
    },
    {
      "src": "<%= asset_path('heart-76x76.png') %>",
      "type": "image/png",
      "sizes": "76x76"
    },
    {
      "src": "<%= asset_path('heart-96x96.png') %>",
      "type": "image/png",
      "sizes": "96x96"
    },
    {
      "src": "<%= asset_path('heart-120x120.png') %>",
      "type": "image/png",
      "sizes": "120x120"
    },
    {
      "src": "<%= asset_path('heart-152x152.png') %>",
      "type": "image/png",
      "sizes": "152x152"
    },
    {
      "src": "<%= asset_path('heart-180x180.png') %>",
      "type": "image/png",
      "sizes": "180x180"
    },
    {
      "src": "<%= asset_path('heart-192x192.png') %>",
      "type": "image/png",
      "sizes": "192x192"
    },
    {
      "src": "<%= asset_path('heart-512x512.png') %>",
      "type": "image/png",
      "sizes": "512x512"
    },
    {
      "src": "<%= asset_path('heart-1200x1200.png') %>",
      "type": "image/png",
      "sizes": "1200x1200"
    }
  ],
  "theme_color": "#EB3349",
  "background_color": "#EB3349",
  "display": "standalone",
  "orientation": "portrait"
}

app/views/service_worker/offline.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1526367790999-0150786686a2?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=28b36a5d126765bdf3912f8535598b88&auto=format&fit=crop&w=1502&q=80');">
  <div class="banner-content">
    <h1>Favores Y Servicios</h1>
    <%= link_to "Pedir Favor", tasks_path, class:"btn home-button btn-lg disabled", disabled: true %>
  </div>
</div>
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1527838016968-2191bb805fc1?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=329f7c874f582c03f1ecccfc5bbe36dd&auto=format&fit=crop&w=1408&q=80');">
  <div class="banner-content">
    <h1>Para Tomar</h1>
    <%= link_to "Ir a Koala", koala_path, class:"btn home-button btn-lg disabled", disabled: true %>
  </div>
</div>
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1528605105345-5344ea20e269?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80');">
  <div class="banner-content">
    <h1>Entretenimiento</h1>
    <%= link_to "Ir a Papelitos", papelitos_path, class:"btn home-button btn-lg disabled", disabled: true %>
  </div>
</div>

app/views/service_worker/service_worker.js.erb
var CACHE_VERSION = 'v1';
var CACHE_NAME = CACHE_VERSION + ':sw-cache-';

function onInstall(event) {
  console.log('[Serviceworker]', "Installing!", event);
  event.waitUntil(
    caches.open(CACHE_NAME).then(function prefill(cache) {
      return cache.addAll([
        '<%= asset_pack_path 'application.js' %>',
        '<%= stylesheet_path 'application.css' %>',
        '/offline.html',
      ]);
    })
  );
}

function onActivate(event) {
  console.log('[Serviceworker]', "Activating!", event);
  event.waitUntil(
    caches.keys().then(function(cacheNames) {
      return Promise.all(
        cacheNames.filter(function(cacheName) {
          // Return true if you want to remove this cache,
          // but remember that caches are shared across
          // the whole origin
          return cacheName.indexOf(CACHE_VERSION) !== 0;
        }).map(function(cacheName) {
          return caches.delete(cacheName);
        })
      );
    })
  );
}

// Borrowed from https://github.com/TalAter/UpUp
function onFetch(event) {
  event.respondWith(
    // try to return untouched request from network first
    fetch(event.request).catch(function() {
      // if it fails, try to return request from the cache
      return caches.match(event.request).then(function(response) {
        if (response) {
          return response;
        }
        // if not found in cache, return default offline content for navigate requests
        if (event.request.mode === 'navigate' ||
          (event.request.method === 'GET' && event.request.headers.get('accept').includes('text/html'))) {
          console.log('[Serviceworker]', "Fetching offline content", event);
          return caches.match('/offline.html');
        }
      })
    })
  );
}

self.addEventListener('install', onInstall);
self.addEventListener('activate', onActivate);
self.addEventListener('fetch', onFetch);